# Generated by Django 6.0.3 on 2026-03-16 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20)),
                ('weekly_premium', models.IntegerField()),
                ('coverage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('daily_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_reason', models.CharField(max_length=200)),
                ('payout_amount', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.worker')),
            ],
        ),
    ]
